<#
.SYNOPSIS
    DirectOutput Framework (DOF R3++) output-middleware adapter for Fried's Retrogaming Kit.
.DESCRIPTION
    DOF is the de-facto output engine of pinball cabinets: it consumes MAME's Win32 output messages
    (mame.ini: output = windows) and drives lamps, solenoids, motors and LED strips through the
    cabinet's controllers. It is DETECTED, never installed as a service and never started by the kit.
    Detection reads a snapshot (processes, ports, devices, tools folder) so tests can inject
    everything. DOF itself lives under C:\DirectOutput - OUTSIDE the RetroBat root contract, which
    drives every deviation below.

    Kit deviations from the downloaded draft (deliberate, permanent):
      * The draft downloaded DOF-R3plus-latest.zip from mjrnet.org, ran Unblock-File over every DLL,
        executed RegisterDirectOutputComObject.exe (HKLM write) and overwrote GlobalConfig_B2SServer.xml
        with Set-Content -Force. The kit does none of that: no downloads, no registry, no COM
        registration, no XML synthesis. Standing up C:\DirectOutput stays manual work by a person.
      * Install therefore also does NOT unpack a -PackagePath: there is no tools\<Name> staging folder
        in DOF's contract (ToolDir = '') and writing into C:\DirectOutput is outside every root the
        kit may touch. The adapter names the official sources; the person deploys them.
      * ToolDir = '' is intentional. The folder guard in Test-DirectOutputFrameworkHardware skips an
        empty ToolDir harmlessly, so the process remains the evidence - the honest one: an installed
        but idle DOF must not flip the mame output key through a dead folder. (Some RetroBat setups
        do ship tools\DirectOutput; if folder evidence is ever wanted, set ToolDir here - the guard
        will pick it up without any other change.)
      * BoardMatchIds is empty: the LED-Wiz boards (0DFA:0001), the PacLED64 (D209:1401) and the
        FAFA clones are EVIDENCE OF THE CONSUMER ADAPTERS that talk HID to the board itself - the kit
        claims USB\VID_0DFA&PID_0001* under MameHooker, never here. The draft matched the whole
        VID_FAFA namespace: FAFA:00F0-00FF is indistinguishable from a Pinscape controller's LedWiz
        emulation unit, so the range stays UNCLAIMED (README, open fact questions).
      * MameOutput = 'windows': DOF listens to the same Win32 broadcast as MameHooker and Hook of the
        Reaper. Two 'windows' adapters are NO OutputModeConflict - they may coexist and the shield
        reports rival listeners; only windows-vs-network is the exclusive decision of mame.ini.
      * SettingsTargets = @() in v1: C:\DirectOutput\Config\*.xml (GlobalConfig, Cabinet.xml) lies
        outside every root contract and the kit has no XML writer; directoutputconfig30.ini is
        generated by DOF's online configuration tool - never invent it here.
#>

function Test-DirectOutputFrameworkHardware {
    [CmdletBinding()]
    param([string] $RetroBatRoot, [hashtable] $Snapshot)
    # No snapshot: read the live machine. With snapshot: pure data, nothing touched.
    if (-not $PSBoundParameters.ContainsKey('Snapshot') -or -not $Snapshot) {
        $Snapshot = Get-OutputSystemSnapshot -RetroBatRoot $RetroBatRoot
    }
    $info = Get-DirectOutputFrameworkAdapterInfo
    foreach ($p in @(Get-OutputAdapterValue $info 'DetectProcesses')) {
        if (@($Snapshot.Processes) -contains $p.ToLowerInvariant()) { return $true }
    }
    foreach ($port in @(Get-OutputAdapterValue $info 'DetectPorts')) {
        if (@($Snapshot.Ports) -contains [int]$port) { return $true }
    }
    foreach ($d in @($Snapshot.Devices | Where-Object { $_ })) {
        $id = (Get-LightgunDeviceId $d).ToUpperInvariant()
        foreach ($m in @(Get-OutputAdapterValue $info 'BoardMatchIds')) { if ($id -like $m.ToUpperInvariant()) { return $true } }
    }
    # Inert while ToolDir = '' (DOF lives in C:\DirectOutput, outside the root contract); the shape
    # stays so a future tools\DirectOutput decision becomes evidence without touching this function.
    $toolDir = [string](Get-OutputAdapterValue $info 'ToolDir')
    if ($RetroBatRoot -and $toolDir) {
        if (Test-Path -LiteralPath (Join-Path $RetroBatRoot "tools\$toolDir") -PathType Container) { return $true }
    }
    $false
}

function Get-DirectOutputFrameworkAdapterInfo {
    @{
        ToolDir         = ''                                          # C:\DirectOutput is outside the RetroBat root contract (see header)
        DetectProcesses = @('DirectOutput')                           # without .exe, case-insensitive
        DetectPorts     = @()                                         # Win32 message consumer - it owns no TCP port
        BoardMatchIds   = @()                                         # boards are the consumer adapters' evidence, never the framework's (see header)
        MameOutput      = 'windows'                                   # mame.ini: output = windows (Win32 messages)
        SettingsTargets = @()                                         # DOF's XML world + directoutputconfig30.ini stay with the person and the online config tool
        Links           = @{
            'DOF R3 readme'                   = 'http://mjrnet.org/pinscape/DOF%20R3%20Readme.htm'
            'DirectOutputFramework (vpinball)' = 'https://github.com/vpinball/DirectOutputFramework'
        }
        Notes           = 'Win32 output consumer; C:\DirectOutput-Setup (COM-Registration, Cabinet.xml) ist Handarbeit.'
    }
}

# Deliberately does NOT download AND does NOT unpack: unlike the portable tools, DOF has no tools\
# staging folder (ToolDir = '') and its setup (COM registration, C:\DirectOutput layout) is manual
# work. Passing -PackagePath changes nothing here - the adapter only names the official sources and
# states that the person installs and starts DOF themselves. Nothing is ever registered or killed.
function Install-DirectOutputFrameworkSoftware {
    [CmdletBinding()]
    param([string] $RetroBatRoot, [string] $PackagePath, [switch] $Approved)
    $info = Get-DirectOutputFrameworkAdapterInfo
    foreach ($k in @($info.Links.Keys)) { Write-KitLog (Get-KitText 'Output.Adapter.SoftwareLink' -f $k, $info.Links[$k]) }
    Write-KitLog (Get-KitText 'Output.Adapter.NoService') -Level Info
    $false
}

function Configure-DirectOutputFrameworkProfile {
    [CmdletBinding(SupportsShouldProcess)]
    param([string] $RetroBatRoot)
    # Routes through the core: it writes mame.ini output = windows when the detected tools agree on
    # one mode and skips the key on a windows-vs-network conflict. DOF's own config files stay
    # unmanaged in v1 (SettingsTargets = @(), see header) - this function never writes them by hand.
    Set-OutputMiddlewareConfiguration -Names @('DirectOutputFramework') -RetroBatRoot $RetroBatRoot -Confirm:$false
}

# Interference shield, kit style: DOF shares the Win32 output broadcast with every other listener
# (MAMEHooker, Hook of the Reaper, LEDBlinky - two consumers mean double-driven events). The shield
# only REPORTS rivals by name, read-only through Get-Process; it never kills anything, never touches
# the registry (no HKLM) and DOF owns no TCP port, so the port loop stays empty by design.
function Set-DirectOutputFrameworkInterferenceShield {
    [CmdletBinding()]
    param([string] $RetroBatRoot, [switch] $Disable)
    if ($Disable) { return }
    $info = Get-DirectOutputFrameworkAdapterInfo
    foreach ($p in @(Get-OutputAdapterValue $info 'DetectPorts')) {
        $owner = @(Get-NetTCPConnection -State Listen -LocalPort $p -ErrorAction SilentlyContinue |
            ForEach-Object { (Get-Process -Id $_.OwningProcess -ErrorAction SilentlyContinue).Name } | Select-Object -Unique)
        if ($owner.Count) { Write-KitLog (Get-KitText 'Output.Shield.PortOwner' -f $p, ($owner -join ', ')) -Level Info }
    }
    # Read-only glance at rival Win32 message listeners (report only, no action):
    $rivals = @(Get-Process -ErrorAction SilentlyContinue | Where-Object { $_.Name -in @('MameHooker', 'Mamehooker51', 'HookOfTheReaper', 'Hook of the Reaper', 'HOTR', 'LEDBlinky', 'LEDBlinkyService') } | ForEach-Object { $_.Name } | Select-Object -Unique)
    if ($rivals.Count) { Write-KitLog (Get-KitText 'Output.Shield.RivalListener' -f 'Win32 output messages', ($rivals -join ', ')) -Level Info }
}
